### ISSUE TITLE
Add versions to estuary_client

### ISSUE THREAD

**Issue by gmelodie** [application-research/pestuary#17]
As it is, `estuary_client` has no version numbers, this leads pip to always get the latest version of estuary_client. When trying to force pip to use `pestuary v1.0.7` it kept complaining about `estuary_client` having a wrong variable name.
```bash
Traceback (most recent call last):
  File "/home/gmelodie/repos/estuary-helper-bot/estuary_helper.py", line 9, in <module>
    import pestuary
  File "/home/gmelodie/repos/estuary-helper-bot/my-virtualenv/lib/python3.10/site-packages/pestuary.py", line 37, in <module>
    peeringApi = estuary_client.PeeringApi(estuary_client.ApiClient(configuration))
AttributeError: module 'estuary_client' has no attribute 'PeeringApi'. Did you mean: 'PinningApi'?
```

This happened because although `pestuary` was downgraded, `estuary_client` was kept in the "latest version" since there's no versions or version requirements attached to it

**Comment by gmelodie** [comment]
Oops! It seems there _are_ versions, but I think either `estuary_client` needs an update or `pestuary` needs to adapt to it. I got `pestuary.content_add()` to work with
```
pestuary==1.0.7
estuary_client==1.0.3
```
